name: Test Site
sizeX: 16
sizeY: 8
minRooms: 32
maxRooms: 64
straightness: 8
weights:
  creatureCount:
    - 32
    - 16
    - 4
    - 1
  creatureType:
    android: 30
    drone: 10
    avatar: 5
  roomType: {}
