name: Test Site
sizeX: 16
sizeY: 8
minRooms: 32
maxRooms: 64
straightness: 8
weights:
  creatureCount:
    - 32
    - 16
    - 4
    - 1
  creatureType:
    creature-android: 30
    creature-drone: 10
    creature-avatar: 5
  roomType: {}
